# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyBaseProgect' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for MyBaseProgect
  pod 'AFNetworking',  '~> 3.1.0'
  pod 'MBProgressHUD'#HUD的提示
  pod 'SVProgressHUD'
  pod 'SDWebImage',  '~> 4.0.0’
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'IQKeyboardManager'
  pod 'Masonry'
  pod 'pop'
  pod 'ReactiveCocoa', '~>2.5'
  pod 'RMessage'
  pod 'Reachability', '~> 3.2'
  pod 'ZYCornerRadius', '~> 1.0.2'#高性能圆角,利用runtime实现
  pod 'YYKit'
end
